import { Express } from "express";
import healthCheck from "./v1/healthCheck.route";
import userRoutes from "./v1/user.route";
import purchaseOrder from "./v1/purchaseOrderRoute";
import profileRoutes from "./v1/profile.route";
import enquiryRoutes from "./v1/enquiry.routes";
import faqRoutes from "./v1/faq.routes";
import invoiceRoutes from "./v1/invoices.routes";
import advancePaymentRoutes from "./v1/advancePayment.route";
import vendorRoutes from "./v1/vendor.route";
import SOARoutes from "./v1/SOARoutes";
import responseRoutes from "./v1/response.routes";
import logisticInvoiceRoutes from "./v1/logisticInvoice.route";
import notificationRoutes from "./v1/notificationRoute";
import dashboard from "./v1/dashboard.route";
import employeeRoutes from "./v1/employee.route";
import uploadFile from "./v1/uploadRoutes";
import apInvoiceOcrRoutes from "./v1/apInvoiceOcr.route";
import extractionPromptConfigRoutes from "./v1/extractionPromptConfig.route";
import invoiceConfigRoutes from "./v1/invoiceConfig.route";
import sapSsoRoutes from "./v1/sapSso.route";
import entraSsoRoutes from "./v1/entraSso.route";
import emailTemplateRoutes from "./v1/emailTemplate.route";
import essaInvoiceRoutes from "./v1/essaInvoice.route";
import essaAuditRoutes from "./v1/essaAudit.route";
import slaRoutes from "./v1/sla.route";
import essaVendorRoutes from "./v1/essaVendor.route";
import essaUserRoutes from "./v1/essaUser.route";

const initializeRoutes = (app: Express) => {
  // Routes
  app.use("/vendor-portal", healthCheck);
  app.use("/vendor-portal/auth", sapSsoRoutes);
  app.use("/vendor-portal/auth", entraSsoRoutes);
  app.use("/vendor-portal/users", userRoutes);
  app.use("/vendor-portal/notification", notificationRoutes);
  app.use("/vendor-portal/purchaseOrder", purchaseOrder);
  app.use("/vendor-portal/profile", profileRoutes);
  app.use("/vendor-portal/enquiry", enquiryRoutes);
  app.use("/vendor-portal/faq", faqRoutes);
  app.use("/vendor-portal/invoice", invoiceRoutes);
  app.use("/vendor-portal/SOA", SOARoutes);
  app.use("/vendor-portal/advancePayment", advancePaymentRoutes);
  app.use("/vendor-portal/vendor", vendorRoutes);
  app.use("/vendor-portal/response", responseRoutes);
  app.use("/vendor-portal/logisticInvoice", logisticInvoiceRoutes);
  app.use("/vendor-portal/dashboard", dashboard);
  app.use("/vendor-portal/employee", employeeRoutes);
  app.use("/vendor-portal/file", uploadFile);
  app.use("/vendor-portal/ap-invoice-ocr", apInvoiceOcrRoutes);
  app.use("/vendor-portal/extraction-prompt-config", extractionPromptConfigRoutes);
  app.use("/vendor-portal/invoice-config", invoiceConfigRoutes);
  app.use("/vendor-portal/essa/email-templates", emailTemplateRoutes);
  app.use("/vendor-portal/essa/invoices", essaInvoiceRoutes);
  app.use("/vendor-portal/essa/audit-logs", essaAuditRoutes);
  app.use("/vendor-portal/essa/sla", slaRoutes);
  app.use("/vendor-portal/essa/vendors", essaVendorRoutes);
  app.use("/vendor-portal/essa/users", essaUserRoutes);
};

export default initializeRoutes;
