export const SET_LOGISTIC_INVOICES_LIST = 'SET_LOGISTIC_INVOICES_LIST';
export const SET_LOGISTIC_INVOICE = 'SET_LOGISTIC_INVOICE';
export const SET_LOGISTIC_INVOICE_DETAILS_LIST = 'SET_LOGISTIC_INVOICE_DETAILS_LIST';
export const SET_COMPLETE_LOGISTIC_INVOICE_DETAIL = 'SET_COMPLETE_LOGISTIC_INVOICE_DETAIL'