-- Migration 013 (Postgres): Extraction prompt templates master data
-- Category → Invoice Type → Type-Document (join) → Fields + Prompt Template
-- Soft delete only ("IsDeleted"). FKs use NO ACTION — no ON DELETE CASCADE.
-- Unique codes/names apply to all rows including soft-deleted (codes stay reserved).
-- DisplayName is included on AP_EXTRACTION_FIELD.
-- Quoted identifiers match the MSSQL→Postgres migration (PascalCase columns).

-- ---------------------------------------------------------------------------
-- AP_EXTRACTION_CATEGORY
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_EXTRACTION_CATEGORY" (
  "CategoryId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Code" VARCHAR(50) NOT NULL,
  "Name" VARCHAR(200) NOT NULL,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_EXTRACTION_CATEGORY" PRIMARY KEY ("CategoryId"),
  CONSTRAINT "UQ_AP_EXTRACTION_CATEGORY_Code" UNIQUE ("Code")
);

-- ---------------------------------------------------------------------------
-- AP_EXTRACTION_INVOICE_TYPE
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_EXTRACTION_INVOICE_TYPE" (
  "InvoiceTypeId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "CategoryId" BIGINT NOT NULL,
  "Code" VARCHAR(50) NOT NULL,
  "Name" VARCHAR(200) NOT NULL,
  "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_EXTRACTION_INVOICE_TYPE" PRIMARY KEY ("InvoiceTypeId"),
  CONSTRAINT "UQ_AP_EXTRACTION_INVOICE_TYPE_Code" UNIQUE ("Code"),
  CONSTRAINT "FK_AP_EXTRACTION_INVOICE_TYPE_Category"
    FOREIGN KEY ("CategoryId") REFERENCES "AP_EXTRACTION_CATEGORY" ("CategoryId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_INVOICE_TYPE_CategoryId"
  ON "AP_EXTRACTION_INVOICE_TYPE" ("CategoryId");

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_INVOICE_TYPE_IsDeleted"
  ON "AP_EXTRACTION_INVOICE_TYPE" ("IsDeleted");

-- ---------------------------------------------------------------------------
-- AP_EXTRACTION_DOCUMENT (normalized catalog)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_EXTRACTION_DOCUMENT" (
  "DocumentId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Code" VARCHAR(50) NOT NULL,
  "Name" VARCHAR(200) NOT NULL,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_EXTRACTION_DOCUMENT" PRIMARY KEY ("DocumentId"),
  CONSTRAINT "UQ_AP_EXTRACTION_DOCUMENT_Code" UNIQUE ("Code"),
  CONSTRAINT "UQ_AP_EXTRACTION_DOCUMENT_Name" UNIQUE ("Name")
);

-- ---------------------------------------------------------------------------
-- AP_EXTRACTION_TYPE_DOCUMENT (invoice type ↔ document join)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_EXTRACTION_TYPE_DOCUMENT" (
  "TypeDocumentId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "InvoiceTypeId" BIGINT NOT NULL,
  "DocumentId" BIGINT NOT NULL,
  "IsEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
  "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_EXTRACTION_TYPE_DOCUMENT" PRIMARY KEY ("TypeDocumentId"),
  CONSTRAINT "UQ_AP_EXTRACTION_TYPE_DOCUMENT_Type_Doc" UNIQUE ("InvoiceTypeId", "DocumentId"),
  CONSTRAINT "FK_AP_EXTRACTION_TYPE_DOCUMENT_InvoiceType"
    FOREIGN KEY ("InvoiceTypeId") REFERENCES "AP_EXTRACTION_INVOICE_TYPE" ("InvoiceTypeId")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "FK_AP_EXTRACTION_TYPE_DOCUMENT_Document"
    FOREIGN KEY ("DocumentId") REFERENCES "AP_EXTRACTION_DOCUMENT" ("DocumentId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_TYPE_DOCUMENT_InvoiceTypeId"
  ON "AP_EXTRACTION_TYPE_DOCUMENT" ("InvoiceTypeId");

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_TYPE_DOCUMENT_DocumentId"
  ON "AP_EXTRACTION_TYPE_DOCUMENT" ("DocumentId");

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_TYPE_DOCUMENT_IsDeleted"
  ON "AP_EXTRACTION_TYPE_DOCUMENT" ("IsDeleted");

-- ---------------------------------------------------------------------------
-- AP_EXTRACTION_FIELD (scoped to a type-document pairing)
-- FieldName = JSON / prompt key; DisplayName = UI label; Hint = extraction guidance
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_EXTRACTION_FIELD" (
  "FieldId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "TypeDocumentId" BIGINT NOT NULL,
  "FieldName" VARCHAR(200) NOT NULL,
  "DisplayName" VARCHAR(200) NULL,
  "Hint" TEXT NULL,
  "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_EXTRACTION_FIELD" PRIMARY KEY ("FieldId"),
  CONSTRAINT "FK_AP_EXTRACTION_FIELD_TypeDocument"
    FOREIGN KEY ("TypeDocumentId") REFERENCES "AP_EXTRACTION_TYPE_DOCUMENT" ("TypeDocumentId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

ALTER TABLE "AP_EXTRACTION_FIELD"
  ADD COLUMN IF NOT EXISTS "DisplayName" VARCHAR(200) NULL;

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_FIELD_TypeDocumentId"
  ON "AP_EXTRACTION_FIELD" ("TypeDocumentId");

CREATE INDEX IF NOT EXISTS "IX_AP_EXTRACTION_FIELD_IsDeleted"
  ON "AP_EXTRACTION_FIELD" ("IsDeleted");

-- ---------------------------------------------------------------------------
-- AP_EXTRACTION_PROMPT_TEMPLATE (one per invoice type)
-- IsManuallyEdited: when true, regenerate must not silently overwrite PromptText
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_EXTRACTION_PROMPT_TEMPLATE" (
  "PromptTemplateId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "InvoiceTypeId" BIGINT NOT NULL,
  "PromptText" TEXT NULL,
  "IsManuallyEdited" BOOLEAN NOT NULL DEFAULT FALSE,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_EXTRACTION_PROMPT_TEMPLATE" PRIMARY KEY ("PromptTemplateId"),
  CONSTRAINT "UQ_AP_EXTRACTION_PROMPT_TEMPLATE_InvoiceTypeId" UNIQUE ("InvoiceTypeId"),
  CONSTRAINT "FK_AP_EXTRACTION_PROMPT_TEMPLATE_InvoiceType"
    FOREIGN KEY ("InvoiceTypeId") REFERENCES "AP_EXTRACTION_INVOICE_TYPE" ("InvoiceTypeId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);
