-- Migration 014: Align ESSA SLA columns with the domain types (SlaPolicy / SlaInstance).

ALTER TABLE "ESSA_SLA_POLICY" ADD COLUMN IF NOT EXISTS "ChangeSummary" VARCHAR(500) NULL;
ALTER TABLE "ESSA_SLA_POLICY" ADD COLUMN IF NOT EXISTS "RetiredAt" TIMESTAMP NULL;
ALTER TABLE "ESSA_SLA_POLICY" ADD COLUMN IF NOT EXISTS "LastTestedAt" TIMESTAMP NULL;

ALTER TABLE "ESSA_SLA_INSTANCE" ADD COLUMN IF NOT EXISTS "PolicyVersion" INTEGER NULL;
