-- Migration 014 (Postgres): SAP field mapping + document validation rules
-- Scope: InvoiceTypeId (same grain as Fields to Capture / extraction prompts)
-- Soft delete only ("IsDeleted"). FKs use NO ACTION — no ON DELETE CASCADE.
-- Quoted identifiers match MSSQL→Postgres PascalCase columns.

-- ---------------------------------------------------------------------------
-- AP_INVOICE_CONFIG_VERSION
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_INVOICE_CONFIG_VERSION" (
  "ConfigVersionId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "InvoiceTypeId" BIGINT NOT NULL,
  "VersionCode" VARCHAR(20) NOT NULL,
  "VersionLabel" VARCHAR(100) NULL,
  "EffectiveFrom" DATE NOT NULL,
  "EffectiveTo" DATE NULL,
  "Status" VARCHAR(20) NOT NULL DEFAULT 'Active',
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_INVOICE_CONFIG_VERSION" PRIMARY KEY ("ConfigVersionId"),
  CONSTRAINT "UQ_AP_INVOICE_CONFIG_VERSION_Type_Code" UNIQUE ("InvoiceTypeId", "VersionCode"),
  CONSTRAINT "CK_AP_INVOICE_CONFIG_VERSION_Status" CHECK ("Status" IN ('Active', 'Inactive')),
  CONSTRAINT "FK_AP_INVOICE_CONFIG_VERSION_InvoiceType"
    FOREIGN KEY ("InvoiceTypeId") REFERENCES "AP_EXTRACTION_INVOICE_TYPE" ("InvoiceTypeId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "IX_AP_INVOICE_CONFIG_VERSION_InvoiceTypeId"
  ON "AP_INVOICE_CONFIG_VERSION" ("InvoiceTypeId");

CREATE INDEX IF NOT EXISTS "IX_AP_INVOICE_CONFIG_VERSION_Type_Status_Deleted"
  ON "AP_INVOICE_CONFIG_VERSION" ("InvoiceTypeId", "Status", "IsDeleted");

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_AP_INVOICE_CONFIG_VERSION_OneActive"
  ON "AP_INVOICE_CONFIG_VERSION" ("InvoiceTypeId")
  WHERE "Status" = 'Active' AND "IsDeleted" = FALSE;

-- ---------------------------------------------------------------------------
-- AP_SAP_FIELD_MAPPING
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_SAP_FIELD_MAPPING" (
  "MappingId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ConfigVersionId" BIGINT NOT NULL,
  "FieldId" BIGINT NULL,
  "CapturedFieldCode" VARCHAR(100) NOT NULL,
  "CapturedFieldDescription" VARCHAR(200) NULL,
  "SapTable" VARCHAR(50) NULL,
  "SapFieldName" VARCHAR(100) NOT NULL,
  "SapFieldDescription" VARCHAR(200) NULL,
  "ValidationType" VARCHAR(30) NOT NULL,
  "ToleranceType" VARCHAR(30) NOT NULL,
  "ToleranceValue" DECIMAL(18,4) NULL,
  "ToleranceMin" DECIMAL(18,4) NULL,
  "ToleranceMax" DECIMAL(18,4) NULL,
  "IsMandatory" BOOLEAN NOT NULL DEFAULT TRUE,
  "Status" VARCHAR(20) NOT NULL DEFAULT 'Active',
  "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_SAP_FIELD_MAPPING" PRIMARY KEY ("MappingId"),
  CONSTRAINT "CK_AP_SAP_FIELD_MAPPING_ValidationType" CHECK (
    "ValidationType" IN ('EXACT_MATCH', 'DATE_MATCH', 'AMOUNT_MATCH', 'CODE_MATCH', 'LIST_MATCH')
  ),
  CONSTRAINT "CK_AP_SAP_FIELD_MAPPING_ToleranceType" CHECK (
    "ToleranceType" IN ('EXACT', 'DAYS', 'PERCENT', 'RANGE')
  ),
  CONSTRAINT "CK_AP_SAP_FIELD_MAPPING_Status" CHECK ("Status" IN ('Active', 'Inactive')),
  CONSTRAINT "FK_AP_SAP_FIELD_MAPPING_ConfigVersion"
    FOREIGN KEY ("ConfigVersionId") REFERENCES "AP_INVOICE_CONFIG_VERSION" ("ConfigVersionId")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "FK_AP_SAP_FIELD_MAPPING_Field"
    FOREIGN KEY ("FieldId") REFERENCES "AP_EXTRACTION_FIELD" ("FieldId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "IX_AP_SAP_FIELD_MAPPING_ConfigVersionId"
  ON "AP_SAP_FIELD_MAPPING" ("ConfigVersionId");

CREATE INDEX IF NOT EXISTS "IX_AP_SAP_FIELD_MAPPING_Config_Deleted"
  ON "AP_SAP_FIELD_MAPPING" ("ConfigVersionId", "IsDeleted");

CREATE INDEX IF NOT EXISTS "IX_AP_SAP_FIELD_MAPPING_Config_Captured"
  ON "AP_SAP_FIELD_MAPPING" ("ConfigVersionId", "CapturedFieldCode");

CREATE INDEX IF NOT EXISTS "IX_AP_SAP_FIELD_MAPPING_FieldId"
  ON "AP_SAP_FIELD_MAPPING" ("FieldId");

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_AP_SAP_FIELD_MAPPING_Config_Captured_Active"
  ON "AP_SAP_FIELD_MAPPING" ("ConfigVersionId", "CapturedFieldCode")
  WHERE "IsDeleted" = FALSE;

-- ---------------------------------------------------------------------------
-- AP_DOCUMENT_VALIDATION_RULE
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_DOCUMENT_VALIDATION_RULE" (
  "RuleId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ConfigVersionId" BIGINT NOT NULL,
  "DocumentId" BIGINT NULL,
  "DocumentTitle" VARCHAR(200) NOT NULL,
  "RuleCode" VARCHAR(50) NULL,
  "RuleName" VARCHAR(200) NOT NULL,
  "CheckScope" VARCHAR(30) NOT NULL,
  "IsMandatory" BOOLEAN NOT NULL DEFAULT TRUE,
  "MissingAction" VARCHAR(20) NOT NULL,
  "ContentValidation" BOOLEAN NOT NULL DEFAULT TRUE,
  "WorkflowImpact" VARCHAR(100) NULL,
  "WorkflowImpactDetail" VARCHAR(500) NULL,
  "Status" VARCHAR(20) NOT NULL DEFAULT 'Active',
  "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_DOCUMENT_VALIDATION_RULE" PRIMARY KEY ("RuleId"),
  CONSTRAINT "CK_AP_DOCUMENT_VALIDATION_RULE_CheckScope" CHECK (
    "CheckScope" IN ('AVAILABILITY_CONTENT', 'AVAILABILITY_ONLY')
  ),
  CONSTRAINT "CK_AP_DOCUMENT_VALIDATION_RULE_MissingAction" CHECK (
    "MissingAction" IN ('BLOCK', 'WARNING')
  ),
  CONSTRAINT "CK_AP_DOCUMENT_VALIDATION_RULE_Status" CHECK ("Status" IN ('Active', 'Inactive')),
  CONSTRAINT "FK_AP_DOCUMENT_VALIDATION_RULE_ConfigVersion"
    FOREIGN KEY ("ConfigVersionId") REFERENCES "AP_INVOICE_CONFIG_VERSION" ("ConfigVersionId")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "FK_AP_DOCUMENT_VALIDATION_RULE_Document"
    FOREIGN KEY ("DocumentId") REFERENCES "AP_EXTRACTION_DOCUMENT" ("DocumentId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "IX_AP_DOCUMENT_VALIDATION_RULE_ConfigVersionId"
  ON "AP_DOCUMENT_VALIDATION_RULE" ("ConfigVersionId");

CREATE INDEX IF NOT EXISTS "IX_AP_DOCUMENT_VALIDATION_RULE_Config_Deleted"
  ON "AP_DOCUMENT_VALIDATION_RULE" ("ConfigVersionId", "IsDeleted");

CREATE INDEX IF NOT EXISTS "IX_AP_DOCUMENT_VALIDATION_RULE_DocumentId"
  ON "AP_DOCUMENT_VALIDATION_RULE" ("DocumentId");

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_AP_DOCUMENT_VALIDATION_RULE_Config_RuleCode"
  ON "AP_DOCUMENT_VALIDATION_RULE" ("ConfigVersionId", "RuleCode")
  WHERE "RuleCode" IS NOT NULL AND "IsDeleted" = FALSE;
