-- Migration 025 (Postgres): Rule-metadata columns on SAP mapping + document rules
-- Architecture Option A — do not merge tables; do not change DisplayOrder or MissingAction.

-- ---------------------------------------------------------------------------
-- AP_SAP_FIELD_MAPPING
-- ---------------------------------------------------------------------------
ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "Scope" VARCHAR(30) NOT NULL DEFAULT 'DOCUMENT';

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "Severity" VARCHAR(20) NOT NULL DEFAULT 'ERROR';

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "OverrideAllowed" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "OverrideRole" VARCHAR(50) NULL;

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "HandlerKey" VARCHAR(100) NULL;

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "OutcomeCode" VARCHAR(20) NULL;

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "RuleEffectiveFrom" DATE NULL;

ALTER TABLE "AP_SAP_FIELD_MAPPING"
  ADD COLUMN IF NOT EXISTS "RuleEffectiveTo" DATE NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'CK_AP_SAP_FIELD_MAPPING_Scope'
  ) THEN
    ALTER TABLE "AP_SAP_FIELD_MAPPING"
      ADD CONSTRAINT "CK_AP_SAP_FIELD_MAPPING_Scope"
        CHECK ("Scope" IN ('GLOBAL', 'CATEGORY', 'DOCUMENT', 'FIELD', 'CROSS_DOCUMENT'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'CK_AP_SAP_FIELD_MAPPING_Severity'
  ) THEN
    ALTER TABLE "AP_SAP_FIELD_MAPPING"
      ADD CONSTRAINT "CK_AP_SAP_FIELD_MAPPING_Severity"
        CHECK ("Severity" IN ('INFO', 'WARNING', 'ERROR', 'HARD_FAIL'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_AP_SAP_FIELD_MAPPING_OutcomeCode"
  ON "AP_SAP_FIELD_MAPPING" ("OutcomeCode")
  WHERE "OutcomeCode" IS NOT NULL AND "IsDeleted" = FALSE;

-- ---------------------------------------------------------------------------
-- AP_DOCUMENT_VALIDATION_RULE
-- MissingAction CHECK (BLOCK/WARNING) is intentionally left unchanged.
-- ---------------------------------------------------------------------------
ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "Scope" VARCHAR(30) NOT NULL DEFAULT 'DOCUMENT';

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "Severity" VARCHAR(20) NOT NULL DEFAULT 'ERROR';

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "OverrideAllowed" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "OverrideRole" VARCHAR(50) NULL;

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "HandlerKey" VARCHAR(100) NULL;

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "OutcomeCode" VARCHAR(20) NULL;

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "RuleEffectiveFrom" DATE NULL;

ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
  ADD COLUMN IF NOT EXISTS "RuleEffectiveTo" DATE NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'CK_AP_DOCUMENT_VALIDATION_RULE_Scope'
  ) THEN
    ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
      ADD CONSTRAINT "CK_AP_DOCUMENT_VALIDATION_RULE_Scope"
        CHECK ("Scope" IN ('GLOBAL', 'CATEGORY', 'DOCUMENT', 'FIELD', 'CROSS_DOCUMENT'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'CK_AP_DOCUMENT_VALIDATION_RULE_Severity'
  ) THEN
    ALTER TABLE "AP_DOCUMENT_VALIDATION_RULE"
      ADD CONSTRAINT "CK_AP_DOCUMENT_VALIDATION_RULE_Severity"
        CHECK ("Severity" IN ('INFO', 'WARNING', 'ERROR', 'HARD_FAIL'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_AP_DOCUMENT_VALIDATION_RULE_OutcomeCode"
  ON "AP_DOCUMENT_VALIDATION_RULE" ("OutcomeCode")
  WHERE "OutcomeCode" IS NOT NULL AND "IsDeleted" = FALSE;
