-- Migration 027 (Postgres): AP_VALIDATION_RUN header + ValidationRunId on results
-- Optional FKs to AP_DOCUMENT / INVOICE_HEADER are added only when no orphans exist.

-- ---------------------------------------------------------------------------
-- AP_VALIDATION_RUN
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AP_VALIDATION_RUN" (
  "ValidationRunId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "InvoiceHeaderId" INTEGER NULL,
  "DocumentId" BIGINT NULL,
  "ConfigVersionId" BIGINT NULL,
  "TriggerEvent" VARCHAR(50) NOT NULL,
  "Status" VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
  "StartedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CompletedAt" TIMESTAMP NULL,
  "TriggeredBy" INTEGER NULL,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "CreatedBy" INTEGER NULL,
  "UpdatedAt" TIMESTAMP NULL,
  "UpdatedBy" INTEGER NULL,
  CONSTRAINT "PK_AP_VALIDATION_RUN" PRIMARY KEY ("ValidationRunId"),
  CONSTRAINT "CK_AP_VALIDATION_RUN_Status" CHECK ("Status" IN ('RUNNING', 'COMPLETED', 'FAILED')),
  CONSTRAINT "FK_AP_VALIDATION_RUN_ConfigVersion"
    FOREIGN KEY ("ConfigVersionId") REFERENCES "AP_INVOICE_CONFIG_VERSION" ("ConfigVersionId")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "IX_AP_VALIDATION_RUN_DocumentId"
  ON "AP_VALIDATION_RUN" ("DocumentId");

CREATE INDEX IF NOT EXISTS "IX_AP_VALIDATION_RUN_InvoiceHeaderId"
  ON "AP_VALIDATION_RUN" ("InvoiceHeaderId");

CREATE INDEX IF NOT EXISTS "IX_AP_VALIDATION_RUN_ConfigVersionId"
  ON "AP_VALIDATION_RUN" ("ConfigVersionId");

-- ---------------------------------------------------------------------------
-- AP_VALIDATION_RESULT.ValidationRunId (nullable — same pattern as migration 015)
-- ---------------------------------------------------------------------------
ALTER TABLE "AP_VALIDATION_RESULT"
  ADD COLUMN IF NOT EXISTS "ValidationRunId" BIGINT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'FK_AP_VALIDATION_RESULT_ValidationRun'
  ) THEN
    ALTER TABLE "AP_VALIDATION_RESULT"
      ADD CONSTRAINT "FK_AP_VALIDATION_RESULT_ValidationRun"
        FOREIGN KEY ("ValidationRunId") REFERENCES "AP_VALIDATION_RUN" ("ValidationRunId")
        ON DELETE NO ACTION ON UPDATE NO ACTION;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_AP_VALIDATION_RESULT_ValidationRunId"
  ON "AP_VALIDATION_RESULT" ("ValidationRunId");

-- ---------------------------------------------------------------------------
-- Logical FKs (skipped when orphan rows exist — do not delete data)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'FK_AP_VALIDATION_RESULT_Document'
  ) THEN
    NULL;
  ELSIF to_regclass('public."AP_DOCUMENT"') IS NULL THEN
    RAISE NOTICE 'Skipping FK_AP_VALIDATION_RESULT_Document: AP_DOCUMENT not found.';
  ELSIF EXISTS (
    SELECT 1
    FROM "AP_VALIDATION_RESULT" r
    WHERE r."DocumentId" IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM "AP_DOCUMENT" d WHERE d."DocumentId" = r."DocumentId"
      )
  ) THEN
    RAISE NOTICE 'Skipping FK_AP_VALIDATION_RESULT_Document: orphan DocumentId values exist.';
  ELSE
    ALTER TABLE "AP_VALIDATION_RESULT"
      ADD CONSTRAINT "FK_AP_VALIDATION_RESULT_Document"
        FOREIGN KEY ("DocumentId") REFERENCES "AP_DOCUMENT" ("DocumentId")
        ON DELETE NO ACTION ON UPDATE NO ACTION;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'FK_AP_VALIDATION_RESULT_InvoiceHeader'
  ) THEN
    NULL;
  ELSIF to_regclass('public."INVOICE_HEADER"') IS NULL THEN
    RAISE NOTICE 'Skipping FK_AP_VALIDATION_RESULT_InvoiceHeader: INVOICE_HEADER not found.';
  ELSIF EXISTS (
    SELECT 1
    FROM "AP_VALIDATION_RESULT" r
    WHERE r."InvoiceHeaderId" IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM "INVOICE_HEADER" h WHERE h."ID" = r."InvoiceHeaderId"
      )
  ) THEN
    RAISE NOTICE 'Skipping FK_AP_VALIDATION_RESULT_InvoiceHeader: orphan InvoiceHeaderId values exist.';
  ELSE
    ALTER TABLE "AP_VALIDATION_RESULT"
      ADD CONSTRAINT "FK_AP_VALIDATION_RESULT_InvoiceHeader"
        FOREIGN KEY ("InvoiceHeaderId") REFERENCES "INVOICE_HEADER" ("ID")
        ON DELETE NO ACTION ON UPDATE NO ACTION;
  END IF;
END $$;
