export const GET_PROFILE_DATA = '/profile/getVendor'
export const GET_EXTENSION_DATA = '/profile/vendor/listExtension'
export const GET_USER_DATA = '/profile/vendor/listSubUser'
export const ADD_USER = '/profile/vendor/addSubUser'
export const GET_CR_PERSONS = '/users/crPerson'
export const GET_PO_CR_PERSONS = '/users/crPersonForPO'
export const GET_ENTITY = '/users/entityDropdown'
export const GET_ENTITY_EXTENSION = '/users/extensionEntityDropdown'
export const ADD_EXTENSION = '/profile/vendor/addExtension'
export const EDIT_PROFILE = '/profile/editVendor'
export const EDIT_INLINE_STATUS = '/vendor/inlineUpdate'
export const TRACK_UPDATES = '/profile/update/status'
export const GET_PAYMENT_TERMS = '/users/paymentterms?type=initial'
export const GET_OTHER_PAYMENT_TERMS = '/users/Registrationpaymentterms '
export const GET_INCOTERMS = '/users/incoterms'
// export const GET_PAYMENTTERMS = '/users/paymentterms'
export const GET_CREDIT_NOTE_PAYMENT_TERMS = '/users/dropdowns?type=CREDIT_NOTE_PAYMENT'
export const UPDATE_PROFILE_IMAGE = '/profile/image'
export const GET_VENDOR_PROFILE_DATA = '/vendor/applications/details'
export const APPROVE_REJECT_VENDOR_APPLICATION = '/vendor/approve-reject'
export const DELETE_USER = '/employee'
export const DELETE_PROFILE_PICTURE = '/profile/deleteProfileImage'
export const EDIT_USER_STATUS = '/employee'
export const NOTIFICATION = '/notification/pullNotification'
export const CLEAR_NOTIFICATION = 'notification/clearNotification'
export const READ_NOTIFICATION = '/notification'
export const STATUS_TOGGLE = '/vendor/updateStatus'
export const UPDATE_NON_PO_ACCESS = '/vendor/nonPOAccess'

